import Register from "./Register";
import Login from "./Login";
import Home from "./Home";
import Cycles from "./Cycles";
import Profile from "./Profile";
import CycleLenderDetails from "./CycleLenderDetails";
import PayApp from "./PaymentDetails";
import PaymentSuccess from "./PaymentSuccess";
import OtpVerified from "./OtpVerification";
export { Register, Login, Home, Cycles, Profile, CycleLenderDetails,PayApp,PaymentSuccess,OtpVerified };
